# Generated by Django 3.1.5 on 2021-02-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='meal',
            name='day',
            field=models.DateTimeField(help_text='Day of the week'),
        ),
    ]
