# Generated by Django 3.1.5 on 2021-02-15 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_user', '0002_auto_20210215_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='day',
            new_name='date',
        ),
    ]
