# Generated by Django 3.1.5 on 2021-03-05 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the recipe', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Description of the recipe')),
                ('servings', models.PositiveSmallIntegerField(blank=True, default=0, help_text='The amount of servings the recipe will yield')),
                ('prep_time', models.CharField(blank=True, default=0, help_text='The preparation time', max_length=50)),
                ('cook_time', models.CharField(blank=True, default=0, help_text='The cooking time', max_length=50)),
                ('url', models.URLField(blank=True)),
                ('recipebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_set', to='recipe_book.recipebook')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.CharField(blank=True, max_length=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_set', to='recipe_book.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_instructions', models.TextField(help_text='Write the instructions of the step here')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_set', to='recipe_book.recipe')),
            ],
        ),
    ]
