# Generated by Django 3.1.5 on 2021-01-16 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.RemoveField(
            model_name='direction',
            name='step_number',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20eae2e8-5eab-40c1-aeae-439481dbe0bb'), primary_key=True, serialize=False),
        ),
    ]
