# Generated by Django 3.1.5 on 2021-01-16 21:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0002_auto_20210116_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ca3c179b-e041-4026-b834-171da23ec67c'), primary_key=True, serialize=False),
        ),
    ]
