# Generated by Django 3.1.5 on 2021-01-16 23:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0003_auto_20210116_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_ingredients', to='recipe_book.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4c7c2257-5cbe-48bd-9468-d9e68fdbd23f'), primary_key=True, serialize=False),
        ),
    ]
