# Generated by Django 3.1.5 on 2021-01-16 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_book', '0004_auto_20210116_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.UUID('14a81af6-157d-4829-a2ee-90ce58964ffe'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipe_book.recipebook'),
        ),
        migrations.AlterField(
            model_name='recipebook',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='has_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
