# Generated by Django 3.1.5 on 2021-01-16 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_book', '0005_auto_20210116_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8f068f55-2355-4b04-8a1a-4cebdc68fc4d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipebook',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
