# Generated by Django 3.1.5 on 2021-01-16 23:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0006_auto_20210116_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe_book.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ee3d5783-15a2-403e-9c21-47eb96cb9dcd'), primary_key=True, serialize=False),
        ),
    ]
