# Generated by Django 3.1.5 on 2021-01-16 23:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0007_auto_20210116_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b9cfa814-4271-40af-a9e6-bb96450f970a'), primary_key=True, serialize=False),
        ),
    ]
