# Generated by Django 3.1.5 on 2021-01-16 23:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0008_auto_20210116_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d846421c-deb0-4c3c-8246-545bf419055d'), primary_key=True, serialize=False),
        ),
    ]
