# Generated by Django 3.1.5 on 2021-01-17 00:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0009_auto_20210116_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='note',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_book.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.UUID('790bd35a-9683-4a62-bc51-2e76582a65aa'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_book.recipebook'),
        ),
    ]
