# Generated by Django 3.1.5 on 2021-01-17 00:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0010_auto_20210117_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5b4e6b07-b65f-43b0-a94d-b19f57da24fc'), primary_key=True, serialize=False),
        ),
    ]
