# Generated by Django 3.1.5 on 2021-01-17 00:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0011_auto_20210117_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_set', to='recipe_book.recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_set', to='recipe_book.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.UUID('212eee15-1051-499d-8724-8cc88089c30c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_set', to='recipe_book.recipebook'),
        ),
    ]
