# Generated by Django 3.1.5 on 2021-01-17 00:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0012_auto_20210117_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.UUID('638f6d2b-7244-4d2a-be35-a29c163bc61a'), primary_key=True, serialize=False),
        ),
    ]
