# Generated by Django 3.1.5 on 2021-01-17 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0013_auto_20210117_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2d22d5aa-a9a4-4097-8f32-ae7f807d1e07'), primary_key=True, serialize=False),
        ),
    ]
