# Generated by Django 3.1.5 on 2021-01-17 22:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0014_auto_20210117_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8cd4fedc-46c9-4f55-bd2b-8b4b7610a93d'), primary_key=True, serialize=False),
        ),
    ]
