# Generated by Django 3.1.5 on 2021-01-17 22:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0015_auto_20210117_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f009fad9-6e5b-4bfc-8ac2-cad83f8ca572'), primary_key=True, serialize=False),
        ),
    ]
