# Generated by Django 3.1.5 on 2021-01-21 22:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0017_auto_20210121_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b39c1e5f-9c7b-44ac-8787-27d9b9f90df6'), primary_key=True, serialize=False),
        ),
    ]
