# Generated by Django 3.1.5 on 2021-01-22 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0019_auto_20210122_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6c76aa32-3647-4aad-9eef-2b91e1cfb556'), primary_key=True, serialize=False),
        ),
    ]
