# Generated by Django 3.1.5 on 2021-01-23 00:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0020_auto_20210122_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.UUID('46b22df1-280e-46b7-881d-b00bbe4f9e0e'), primary_key=True, serialize=False),
        ),
    ]
