# Generated by Django 3.1.4 on 2021-01-23 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0021_auto_20210123_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cb14ac3a-bbc8-4d3b-b4df-864bc938b9b2'), primary_key=True, serialize=False),
        ),
    ]
