# Generated by Django 3.1.5 on 2021-01-14 23:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c2514e93-bbb2-407a-8a25-cf6de36789f4'), primary_key=True, serialize=False),
        ),
    ]
