# Generated by Django 3.1.4 on 2021-01-12 23:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('516c5deb-66db-463f-8e9a-99de508540fd'), primary_key=True, serialize=False),
        ),
    ]
