# Generated by Django 3.1.5 on 2021-01-16 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('51582569-4ebb-4396-ab0e-a8c62fdbff5a'), primary_key=True, serialize=False),
        ),
    ]
