# Generated by Django 3.1.4 on 2021-01-13 02:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210112_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3fae4ed7-a4d3-481b-9e2d-7b04cccf032b'), primary_key=True, serialize=False),
        ),
    ]
