# Generated by Django 3.1.5 on 2021-01-16 23:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210116_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('71b53ca6-7ea6-47e4-b468-9aead63f220e'), primary_key=True, serialize=False),
        ),
    ]
