# Generated by Django 3.1.5 on 2021-01-16 23:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210116_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c145384d-c6f0-468f-b8b2-5b34910b5147'), primary_key=True, serialize=False),
        ),
    ]
