# Generated by Django 3.1.5 on 2021-01-16 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210116_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7f63a6f6-3b85-4dce-ab54-14e985f5a41a'), primary_key=True, serialize=False),
        ),
    ]
