# Generated by Django 3.1.5 on 2021-01-16 23:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210116_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('651a0d3a-932b-40ea-a969-ead7c38b804b'), primary_key=True, serialize=False),
        ),
    ]
