# Generated by Django 3.1.5 on 2021-01-16 23:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210116_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('05f3b2e4-8c12-493d-b044-105224363a8e'), primary_key=True, serialize=False),
        ),
    ]
