# Generated by Django 3.1.5 on 2021-01-17 00:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210116_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2a7d70e8-a946-47de-93a4-0af74056a62b'), primary_key=True, serialize=False),
        ),
    ]
