# Generated by Django 3.1.5 on 2021-01-17 00:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210117_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a5f2cc00-a81f-4d39-9a36-7beeea778dbe'), primary_key=True, serialize=False),
        ),
    ]
