# Generated by Django 3.1.5 on 2021-01-17 00:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210117_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('981366d6-4561-494f-bdb1-496ab64a0c2d'), primary_key=True, serialize=False),
        ),
    ]
