# Generated by Django 3.1.5 on 2021-01-17 22:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210117_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7b64b90f-e052-4397-8bd2-4e941c650ae5'), primary_key=True, serialize=False),
        ),
    ]
