# Generated by Django 3.1.5 on 2021-01-21 21:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210117_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aa97c1a6-f6e3-4356-b4b2-d37dcd0f2888'), primary_key=True, serialize=False),
        ),
    ]
