# Generated by Django 3.1.5 on 2021-01-22 19:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210121_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('76dd272d-c591-4a62-b06b-63558d279d3c'), primary_key=True, serialize=False),
        ),
    ]
