# Generated by Django 3.1.5 on 2021-01-22 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210122_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('34c02ced-5440-4902-9fe6-6cc99eefd383'), primary_key=True, serialize=False),
        ),
    ]
