# Generated by Django 3.1.5 on 2021-01-23 00:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210122_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0c336e16-0ebd-4294-baee-2ff1c62977f1'), primary_key=True, serialize=False),
        ),
    ]
