# Generated by Django 3.1.4 on 2021-01-23 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210123_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5bd57afa-4176-45f4-b932-4c23bedf1812'), primary_key=True, serialize=False),
        ),
    ]
